//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterMVC.FollowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FollowService.IFollowServices")]
    public interface IFollowServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFollowServices/Follow", ReplyAction="http://tempuri.org/IFollowServices/FollowResponse")]
        bool Follow(int idFollow, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFollowServices/Unfollow", ReplyAction="http://tempuri.org/IFollowServices/UnfollowResponse")]
        bool Unfollow(int idunFollow, string user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFollowServicesChannel : TwitterMVC.FollowService.IFollowServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FollowServicesClient : System.ServiceModel.ClientBase<TwitterMVC.FollowService.IFollowServices>, TwitterMVC.FollowService.IFollowServices {
        
        public FollowServicesClient() {
        }
        
        public FollowServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FollowServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FollowServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FollowServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Follow(int idFollow, string user) {
            return base.Channel.Follow(idFollow, user);
        }
        
        public bool Unfollow(int idunFollow, string user) {
            return base.Channel.Unfollow(idunFollow, user);
        }
    }
}
