//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.ServiceProfile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProfile.IProfileServices")]
    public interface IProfileServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServices/PostTweet", ReplyAction="http://tempuri.org/IProfileServices/PostTweetResponse")]
        bool PostTweet(Service.ProfileService pflservice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServices/ReturnIdUser", ReplyAction="http://tempuri.org/IProfileServices/ReturnIdUserResponse")]
        int ReturnIdUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServices/ListTweets", ReplyAction="http://tempuri.org/IProfileServices/ListTweetsResponse")]
        Service.ProfileService[] ListTweets(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServices/SearchTweets", ReplyAction="http://tempuri.org/IProfileServices/SearchTweetsResponse")]
        Service.ProfileService[] SearchTweets(string term);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServices/GetUsername", ReplyAction="http://tempuri.org/IProfileServices/GetUsernameResponse")]
        string GetUsername(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServices/Following", ReplyAction="http://tempuri.org/IProfileServices/FollowingResponse")]
        bool Following(int idfollower, int idfollow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileServices/Follow", ReplyAction="http://tempuri.org/IProfileServices/FollowResponse")]
        void Follow(int idfollower, int idfollow);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServicesChannel : Model.ServiceProfile.IProfileServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServicesClient : System.ServiceModel.ClientBase<Model.ServiceProfile.IProfileServices>, Model.ServiceProfile.IProfileServices {
        
        public ProfileServicesClient() {
        }
        
        public ProfileServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PostTweet(Service.ProfileService pflservice) {
            return base.Channel.PostTweet(pflservice);
        }
        
        public int ReturnIdUser(string username) {
            return base.Channel.ReturnIdUser(username);
        }
        
        public Service.ProfileService[] ListTweets(string username) {
            return base.Channel.ListTweets(username);
        }
        
        public Service.ProfileService[] SearchTweets(string term) {
            return base.Channel.SearchTweets(term);
        }
        
        public string GetUsername(int id) {
            return base.Channel.GetUsername(id);
        }
        
        public bool Following(int idfollower, int idfollow) {
            return base.Channel.Following(idfollower, idfollow);
        }
        
        public void Follow(int idfollower, int idfollow) {
            base.Channel.Follow(idfollower, idfollow);
        }
    }
}
